const COP=n=>'$'+new Intl.NumberFormat('es-CO').format(n);
const P=[
{id:'wundeer',n:'Wundeer',k:'Cliente',s:'Operación / aprobación creativa',pr:'Crítica',loc:'Colombia',date:'21 ago · 10:00',v:9000000,d:'Proyecto integral ya encaminado a operación formal. La reunión para revisar ideas se movió al 21 de agosto a las 10:00 a. m.; todavía no están cerrados los creativos prioritarios.',next:'Revisar y aprobar ideas. Santiago Rosas y Manuel convierten las ideas aprobadas en guiones y ajustan la producción según disponibilidad del cliente.',commercial:['Contrato actual de $9M','Prueba/roadmap integral de 60 días','Pauta de referencia: $1M/mes; distribución por definir con media buyer'],owners:['Santiago Rosas — seguimiento, presupuesto y media buyer','Manuel — guiones / ejecución creativa','Dueño + hijo — aprobación final del cliente'],risks:['Todo contenido requiere aprobación externa antes de publicarse','La primera grabación depende de disponibilidad del cliente','Web/desarrollos aún no están maduros para medir conversión dura'],pending:['Aprobar ideas y creativos','Confirmar fecha definitiva de primera grabación','Definir distribución del presupuesto de pauta'],notes:['Si se graban 4 videos, la entrega prevista era martes a viernes de la semana siguiente; si se graban 5, el quinto saldría el sábado.','El operador de pauta revisa diariamente y reporta cada 15 días al equipo y al cliente.','Métrica temprana prioritaria: reconocimiento/awareness; tráfico y seguidores pueden apoyar la lectura.'],links:[['Prototipo','https://wuundeer-prototype.vercel.app/'],['Pitch','https://manepeqsicoda.github.io/WuunderPitch/']]},
{id:'boga',n:'BOGA',k:'Cliente',s:'Cierre / entrega',pr:'Crítica',loc:'Colombia',date:'18 sep',v:1200000,d:'Sitio casi funcional. La entrega objetivo quedó para el 18 de septiembre. Hay pendientes que no bloquean MVP, pero sí faltan funciones administrativas importantes.',next:'Cerrar MVP, cobrar saldo antes del 1 de septiembre y preparar entrega del 18 de septiembre.',commercial:['Pago final previsto antes del 1 de septiembre','Mantenimiento: $300.000/mes durante 6 meses'],owners:['Equipo de desarrollo','Cuenta / dirección'],risks:['Panel admin todavía no permite cambiar manualmente una cotización','Falta panel para creación de usuarios','Se reportó que algunos usuarios requieren seed en Prisma','Comunicación/documentación entre equipos puede generar reproceso'],pending:['Cambio manual de cotizaciones desde admin','Panel de creación de usuarios','Revisión final de integraciones y pendientes no-MVP'],notes:['No se planea revisión intermedia adicional: la siguiente revisión fuerte es alrededor de la entrega.','Integraciones como creación de paquetes se consideran posteriores/no bloqueantes para MVP.'],links:[['Prototipo','https://quoter-boga-frontend-beta.up.railway.app/'],['Pitch','https://junisama-seven.vercel.app/pitch']]},
{id:'satiro',n:'Sátiro Sushi',k:'Cliente',s:'En desarrollo',pr:'Crítica',loc:'Chía',date:'1 sep',v:12000000,d:'La entrega funcional se mantiene para el 1 de septiembre. El pendiente técnico más relevante es la integración con el sistema POS del restaurante.',next:'Preguntar qué POS usa Sátiro y evaluar integración. Santiago Rosas queda responsable de ese frente.',commercial:['La integración POS es un agregado; no era requisito original de la entrega','Si no está lista, se puede operar con paso manual de datos'],owners:['Santiago Rosas — integración POS','Personal interno de Sátiro — operación manual temporal'],risks:['Aún no se conoce el POS usado por Sátiro','La integración depende de capacidades/API del proveedor POS'],pending:['Identificar POS exacto','Validar mecanismo de integración'],notes:['El cliente ya conoce y acepta el plan B manual.','El POS no bloquea la entrega del 1 de septiembre.'],links:[['Prototipo','https://landing-satiro-demo-production.up.railway.app/']]},
{id:'harbin',n:'Harbin Restaurantes',k:'Prospecto',s:'Pendiente reunión',pr:'Alta',loc:'Bogotá · Chía · Soacha',date:'Por definir',p:30000000,d:'Todavía no se ha podido realizar la reunión. El objetivo de la próxima conversación es obtener aprobación del prototipo y de precios para poder fijar inicio.',next:'El 21 de agosto volver a contactar a Alejandra Suárez para que consulte con la dueña y ayude a destrabar la reunión.',commercial:['Precio actualizado: 30 cuotas de $1.000.000 = $30M','El pago inicia desde el día de la firma','Incluye desarrollo web y funcionalidades','Pauta no incluida','Después de los 30 meses se ofrece mantenimiento aparte'],owners:['Dueña de Harbin — única decisora final','Alejandra Suárez — puente comercial'],risks:['Sin fecha de reunión confirmada'],pending:['Agendar reunión','Aprobar prototipo y precios','Definir fecha de inicio tras aprobación'],notes:['Si la dueña aprueba prototipo y precios, RR puede arrancar de inmediato.'],links:[['Prototipo','https://landing-harbin-demo-production.up.railway.app/']]},
{id:'zapatos',n:'Zapatos',k:'Cliente / oportunidad',s:'Sin iniciar',pr:'Alta',loc:'Colombia',date:'Por definir',d:'El proyecto todavía no ha arrancado. El siguiente paso es programar reunión con Alejandro Zuluaga, dueño, para levantar requerimientos.',next:'Agendar discovery con Alejandro Zuluaga y aterrizar alcance/cotización.',commercial:['Concepto base similar a Wundeer, enfocado en venta al por mayor'],owners:['Alejandro Zuluaga — dueño / decisor','RR Aliados — discovery y propuesta'],risks:['Alcance todavía no levantado'],pending:['Fecha de reunión','Requerimientos','Cotización final'],notes:['La visión preliminar contempla captación abierta desde contenido/pauta/SEO, registro del comprador y solicitud de cotización.','La cotización sería armada manualmente desde un dashboard y enviada en PDF por correo o WhatsApp.','Se contempla seguimiento tipo mini-CRM con estados e historial de cliente, pero estos detalles se definirán en discovery.'],links:[]},
{id:'candilejas',n:'Candilejas',k:'Prospecto',s:'Prototipo en construcción',pr:'Crítica',loc:'Antioquia',date:'21 ago · noche',p:20000000,d:'El prototipo todavía está en construcción. Se presenta el viernes en la noche junto con precio y propuesta, buscando decisión comercial.',next:'Manu termina el prototipo y se presenta a Rafa el viernes en la noche.',commercial:['Precio base: $20M por todas las sedes','Cobertura: proyecto completo por 30 meses','Pronto pago: $18M si se paga en 4 meses','Descuento táctico: $1M por proyecto si Rafa ayuda a cerrar Candilejas y La Banca; usar solo si es necesario'],owners:['Manu — desarrollo del prototipo','Rafa — dueño/contacto clave; probablemente valida con otros involucrados','Alejandra Suárez — presente en la reunión'],risks:['El prototipo completo aún no está terminado'],pending:['Terminar prototipo','Presentar precio y propuesta','Buscar cierre comercial'],notes:['El descuento de $1M aplica sin importar la modalidad de pago, pero no se ofrece de entrada.'],links:[]},
{id:'labanca',n:'La Banca',k:'Prospecto',s:'Prototipo en construcción',pr:'Crítica',loc:'Antioquia',date:'21 ago · noche',p:20000000,d:'Martín desarrolla el prototipo. Se presenta el viernes en la noche, también con Rafa como dueño/contacto clave y buscando decisión comercial.',next:'Finalizar prototipo y presentar propuesta completa el viernes.',commercial:['Precio base: $20M por todas las sedes','Proyecto por 30 meses','Misma opción de pronto pago en 4 meses que Candilejas','Descuento táctico de $1M si Rafa ayuda a cerrar ambos proyectos; solo si hace falta'],owners:['Martín — desarrollo del prototipo','Rafa — dueño/contacto clave','Alejandra Suárez — presente en la reunión'],risks:['Prototipo aún en ejecución'],pending:['Terminar prototipo','Presentar propuesta','Buscar cierre comercial'],notes:[],links:[]},
{id:'marytierra',n:'Mar y Tierra',k:'Prospecto',s:'Preparación de pitch',pr:'Alta',loc:'Zipaquirá',date:'1 sep',p:12000000,d:'Santiago Rosas viajará a Bogotá el 1 de septiembre para presentar prototipo, precio y propuesta comercial completa.',next:'Manu asigna al desarrollador y el prototipo debe estar listo para el 1 de septiembre.',commercial:['Mismo sistema de precios de Sátiro'],owners:['Santiago Rosas — presentación','Manu — asignar desarrollador','Alejandra Suárez — acompaña reunión'],risks:['Todavía no hay desarrollador asignado al prototipo'],pending:['Asignar desarrollador','Construir prototipo','Presentar el 1 de septiembre'],notes:['No se necesita una fecha interna adicional mientras esté listo para la presentación.'],links:[]},
{id:'carreta',n:'La Carreta Zipaquirá',k:'Prospecto',s:'Preparación de pitch',pr:'Alta',loc:'Zipaquirá',date:'1 sep',d:'Va en el mismo business trip del 1 de septiembre con Santiago Rosas. Llevará prototipo, precio y propuesta comercial completa.',next:'Manu debe asignar desarrollador y dejar prototipo listo para el viaje.',commercial:['Mismo sistema comercial de Sátiro'],owners:['Santiago Rosas — presentación','Manu — asignar desarrollador','Alejandra Suárez — puente comercial y presente en reunión'],risks:['No hay desarrollador asignado','Aún no está identificado el decisor exacto; se sabe que es familiar de Alejandra Suárez'],pending:['Asignar desarrollador','Construir prototipo','Identificar decisor'],notes:[],links:[]},
{id:'charles',n:'Charles Brown',k:'Prospecto',s:'Preparación de pitch',pr:'Alta',loc:'Colombia',date:'1 sep',p:12000000,d:'Entra en el mismo business trip del 1 de septiembre. Aún no hay prototipo y se presentará paquete completo: prototipo, precio y propuesta.',next:'Manu asigna desarrollador; preparar demo para Carlos y Braulio.',commercial:['Mismo esquema comercial de Sátiro'],owners:['Carlos — dueño / decisor','Braulio — dueño / decisor','Manu — asignar desarrollador','Alejandra Suárez — presente en reunión'],risks:['No existe prototipo todavía'],pending:['Asignar desarrollador','Construir prototipo','Presentar el 1 de septiembre'],notes:[],links:[]},
{id:'plazoleta',n:'Plazoleta Jardín',k:'Prospecto',s:'Preparación multi-restaurante',pr:'Crítica',loc:'Chía',date:'1 sep',p:72000000,d:'Ocho restaurantes. No hay prototipo todavía; Manu debe asignar desarrollador para llegar al business trip del 1 de septiembre.',next:'Asignar desarrollador, construir prototipo multi-restaurante y preparar decisión con socios.',commercial:['Base: $12M por restaurante','Promoción repetible por bloque: al tomar 3 restaurantes, el 4.º es gratis','Con 8 restaurantes, 2 quedan gratis','Valor resultante para 8 restaurantes: $72M'],owners:['Manu — asignar desarrollador','Andrés — socio clave y también dueño de Sátiro','Alejandra Suárez — presente en reunión'],risks:['No hay prototipo','No se sabe cuántos socios deben aprobar ni cómo toman la decisión'],pending:['Asignar desarrollador','Construir prototipo','Mapear socios y mecanismo de aprobación'],notes:['Andrés no puede aprobar solo; requiere autorización de otros socios.'],links:[]},
{id:'amsterdam',n:'Amsterdam ×3',k:'Prospecto',s:'Correcciones antes de presentación',pr:'Alta',loc:'Aruba',date:'24 ago / ~15 sep',p:15000000,d:'La última reunión fue el 18 de agosto. Hay correcciones pendientes a prototipos para Mico y Juanjo. Alejandra prevé viajar alrededor del 15 de septiembre a Aruba para presentar.',next:'Reunión de coordinación el 21 de agosto para aclarar correcciones; Carlitos debe cerrar correcciones antes del lunes 24.',commercial:['Tres prospectos independientes; referencia histórica $5M cada uno'],owners:['Carlitos — frontend y correcciones','Alejandra Suárez — coordinación/presentación con clientes','Sam / Martín / otro asignado — posible backend posterior'],risks:['Tiempo y calidad de implementación','Carlitos a veces omite correcciones o no despliega; requiere seguimiento cercano','La aprobación final depende de presentación de Alejandra y coordinación externa'],pending:['Definir correcciones exactas','Implementar y desplegar antes del 24','Presentación alrededor del 15 de septiembre','Aprobación para arrancar desarrollo completo'],notes:['Después de la presentación, la aprobación del cliente activa el desarrollo completo.','Quien asista a reunión reporta a Manuel/Santiago; si uno de ellos asiste, sube la documentación.'],links:[['Horizons','https://horizons-lunge-demo.vercel.app/'],['Amsterdam Manor','http://amsterdam-manor-beach-demo.vercel.app/'],['Passion on the Beach','https://passion-on-the-beach-demo.vercel.app/']]},
{id:'globos',n:'Globos',k:'Prospecto',s:'Sin novedades',pr:'Media',loc:'Por definir',date:'Por definir',d:'No hubo actualizaciones durante esta sesión. Sigue sin reunión nueva, alcance definido ni hito concreto.',next:'Esperar nuevo movimiento comercial antes de profundizar.',commercial:[],owners:[],risks:['Sin siguiente hito definido'],pending:['Reunión','Alcance','Fechas'],notes:[],links:[]},
{id:'junisama',n:'Junisama / BOGA legado',k:'Referencia / prospecto',s:'Pendiente indicaciones',pr:'Media',loc:'Colombia',date:'21 ago',d:'Mañana, en reunión con Alejandra Paternina, se recibirán las indicaciones finales para definir qué pasa con este frente.',next:'Documentar las indicaciones de la reunión y decidir continuidad/absorción por BOGA.',commercial:[],owners:['Alejandra Paternina — entrega indicaciones'],risks:['Definición todavía abierta'],pending:['Reunión del 21 de agosto','Actualizar decisión y documentación'],notes:[],links:[]}
];
const E=[
['2026-08-21','10:00','Wundeer','Revisión de ideas','meeting'],['2026-08-21','','Candilejas','Presentación prototipo + propuesta · noche','delivery'],['2026-08-21','','La Banca','Presentación prototipo + propuesta · noche','delivery'],['2026-08-21','','Amsterdam','Reunión de coordinación de correcciones','meeting'],['2026-08-21','','Junisama / BOGA legado','Reunión con Alejandra Paternina','meeting'],['2026-08-24','','Amsterdam','Deadline de correcciones frontend','delivery'],['2026-09-01','','Sátiro Sushi','Entrega funcional','delivery'],['2026-09-01','','Mar y Tierra','Prototipo + precio + propuesta','meeting'],['2026-09-01','','La Carreta','Prototipo + precio + propuesta','meeting'],['2026-09-01','','Charles Brown','Prototipo + precio + propuesta','meeting'],['2026-09-01','','Plazoleta Jardín','Prototipo + precio + propuesta','meeting'],['2026-09-18','','BOGA','Entrega objetivo','delivery'],['2026-09-15','','Amsterdam','Presentaciones en Aruba · fecha aproximada','meeting']
];
const AUDIT=[
['BOGA','En el repositorio revisado hay flujo de cotización y múltiples rutas admin. Se detectaron señales de auth/persistencia de demo que deben endurecerse antes de producción; el repo revisado puede no coincidir exactamente con el deployment de Railway.'],
['Sátiro / Harbin','En el sistema vertical de prototipos conectado se encontraron acciones de catálogo/planes todavía simuladas o con href placeholder, checkout simulado y reservas vía WhatsApp. Para piloto real faltan flujos operativos de extremo a extremo.'],
['Wundeer Pitch','El pitch es una presentación interactiva de 10 slides y está bien resuelto comercialmente, pero conserva cifras/fechas anteriores al acuerdo vigente de $9M y 60 días.'],
['Amsterdam','Los deployments fueron identificados, pero no se logró una prueba end-to-end confiable en navegador durante la auditoría; queda pendiente validación funcional real.']
];
let tab='summary',filter='Todos',q='',month=7,year=2026;
const tabs=[['summary','Resumen'],['projects','Proyectos'],['calendar','Calendario'],['audit','Auditoría']];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function nav(){tabsEl.innerHTML=tabs.map(x=>`<button class="${tab===x[0]?'on':''}" onclick="tab='${x[0]}';render()">${x[1]}${x[0]==='projects'?` · ${P.length}`:''}</button>`).join('')}
function money(p){return p.v?['CONTRATADO',COP(p.v)]:p.p?['PIPELINE',COP(p.p)]:['VALOR','POR DEFINIR']}
function cards(list){return list.length?`<div class="grid">${list.map(p=>{const m=money(p);return `<article class="card" onclick="openP('${p.id}')"><div class="kicker"><span>${esc(p.k)} · ${esc(p.loc)}</span><span>${esc(p.date)}</span></div><h3>${esc(p.n)}</h3><div class="badges"><span class="badge ${p.pr==='Crítica'?'hot':''}">${esc(p.pr)}</span><span class="badge">${esc(p.s)}</span></div><p>${esc(p.d)}</p><div class="next"><span>SIGUIENTE MOVIMIENTO</span>${esc(p.next)}</div><div class="money"><span>${m[0]}</span><b>${m[1]}</b></div></article>`}).join('')}</div>`:'<div class="empty">No hay proyectos con este filtro.</div>'}
function summary(){const contracted=P.reduce((a,p)=>a+(p.v||0),0),pipeline=P.reduce((a,p)=>a+(p.p||0),0),critical=P.filter(p=>p.pr==='Crítica').length,sep=P.filter(p=>p.date.includes('1 sep')).length;return `<section class="metrics"><div class="metric"><span>PROYECTOS REGISTRADOS</span><strong>${P.length}</strong><small>ACTUALIZADOS</small></div><div class="metric income"><span>CONTRATADO CONOCIDO</span><strong>${COP(contracted)}</strong><small>COP</small></div><div class="metric accent"><span>PIPELINE CONOCIDO</span><strong>${COP(pipeline)}</strong><small>NO ES CAJA</small></div><div class="metric"><span>PRIORIDAD CRÍTICA</span><strong>${critical}</strong><small>FRENTES</small></div><div class="metric"><span>HITOS 1 SEP</span><strong>${sep}</strong><small>PROYECTOS</small></div></section><div class="sectionHead"><div><div class="label">FOCO INMEDIATO</div><h2>PRÓXIMOS MOVIMIENTOS</h2></div></div>${cards(P.filter(p=>['wundeer','candilejas','labanca','satiro','plazoleta','harbin'].includes(p.id)))}`}
function projects(){const list=P.filter(p=>(filter==='Todos'||p.k.includes(filter))&&JSON.stringify(p).toLowerCase().includes(q.toLowerCase()));return `<div class="sectionHead"><div><div class="label">RADAR MAESTRO</div><h2>TODOS LOS PROYECTOS</h2></div><div><button class="ghost" onclick="downloadAllMd()">↓ MD</button> <button class="primary" onclick="downloadAllPdf()">↓ PDF</button></div></div><div class="controls"><input placeholder="Buscar proyecto, responsable, riesgo…" value="${esc(q)}" oninput="q=this.value;render()">${['Todos','Cliente','Prospecto'].map(x=>`<button class="chip ${filter===x?'on':''}" onclick="filter='${x}';render()">${x}</button>`).join('')}</div>${cards(list)}`}
function calendar(){const start=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=[...Array(start).fill(0),...Array.from({length:days},(_,i)=>i+1)];return `<div class="sectionHead"><div><div class="label">CALENDARIO OPERATIVO</div><h2>${new Date(year,month).toLocaleDateString('es-CO',{month:'long',year:'numeric'}).toUpperCase()}</h2></div><div><button class="chip" onclick="go(-1)">←</button> <button class="chip" onclick="go(1)">→</button></div></div><div class="calendar"><div class="week">${['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM'].map(x=>`<div>${x}</div>`).join('')}</div><div class="days">${cells.map(d=>d?`<div class="day"><span>${d}</span>${E.filter(e=>{let z=new Date(e[0]+'T12:00:00');return z.getFullYear()===year&&z.getMonth()===month&&z.getDate()===d}).map(e=>`<div class="evt ${e[4]}"><b>${e[1]?e[1]+' · ':''}${esc(e[2])}</b><br>${esc(e[3])}</div>`).join('')}</div>`:'<div class="day"></div>').join('')}</div></div><div class="sectionHead"><div><div class="label">AGENDA CLAVE</div><h2>HITOS DE SESIÓN</h2></div></div><div class="timeline">${E.map(e=>`<div class="tl"><time>${e[0]} ${e[1]}</time><div><b>${esc(e[2])}</b><small>${esc(e[3])}</small></div></div>`).join('')}</div>`}
function go(n){month+=n;if(month<0){month=11;year--}if(month>11){month=0;year++}render()}
function audit(){return `<div class="sectionHead"><div><div class="label">AUDITORÍA TÉCNICA</div><h2>PROTOTIPOS Y MADUREZ</h2></div></div><div class="note">Estas observaciones distinguen entre código/repo revisado y pruebas live. No se debe asumir que un repositorio coincide 1:1 con el deployment si no se verificó.</div><div class="audit">${AUDIT.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></div>`).join('')}</div>`}
function arr(title,a){return a?.length?`## ${title}\n${a.map(x=>'- '+x).join('\n')}\n\n`:''}
function mdProject(p){return `# ${p.n} — Contexto Maestro RR Aliados\n\n**Tipo:** ${p.k}\n**Estado:** ${p.s}\n**Prioridad:** ${p.pr}\n**Ubicación:** ${p.loc}\n**Próxima fecha:** ${p.date}\n**Valor contratado:** ${p.v?COP(p.v):'No aplica / por definir'}\n**Pipeline:** ${p.p?COP(p.p):'No aplica / por definir'}\n\n## Situación actual\n${p.d}\n\n## Próximo movimiento\n${p.next}\n\n${arr('Comercial / precio',p.commercial)}${arr('Responsables',p.owners)}${arr('Riesgos',p.risks)}${arr('Pendientes',p.pending)}${arr('Notas',p.notes)}${p.links?.length?'## Enlaces\n'+p.links.map(x=>`- [${x[0]}](${x[1]})`).join('\n')+'\n\n':''}---\nActualizado desde la sesión RR Aliados del 20/08/2026.`}
function masterMd(){return `# RR Aliados — Project Command Center\n\nActualización de sesión: 20/08/2026\n\n${P.map(mdProject).join('\n\n')}\n\n# Auditoría técnica\n\n${AUDIT.map(x=>`## ${x[0]}\n${x[1]}`).join('\n\n')}`}
function blobDownload(text,type,name){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function downloadMd(id){const p=P.find(x=>x.id===id);blobDownload(mdProject(p),'text/markdown;charset=utf-8',`${id}-contexto-maestro.md`)}
function downloadAllMd(){blobDownload(masterMd(),'text/markdown;charset=utf-8','RR-Aliados-contexto-maestro-2026-08-20.md')}
function pdfText(doc,text,title){doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(title,14,18);doc.setFont('helvetica','normal');doc.setFontSize(9);const lines=doc.splitTextToSize(text,180);let y=27;for(const line of lines){if(y>280){doc.addPage();y=16}doc.text(line,14,y);y+=4.3}}
function downloadPdf(id){if(!window.jspdf){alert('El generador PDF todavía está cargando. Intenta de nuevo en un momento.');return}const p=P.find(x=>x.id===id),doc=new window.jspdf.jsPDF();pdfText(doc,mdProject(p).replace(/[#*_`]/g,''),p.n);doc.save(`${id}-contexto-maestro.pdf`)}
function downloadAllPdf(){if(!window.jspdf){alert('El generador PDF todavía está cargando. Intenta de nuevo en un momento.');return}const doc=new window.jspdf.jsPDF();const text=masterMd().replace(/[#*_`]/g,'');pdfText(doc,text,'RR Aliados — Contexto Maestro');doc.save('RR-Aliados-contexto-maestro-2026-08-20.pdf')}
function listPanel(title,a){return `<div class="panel"><span>${title}</span>${a?.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Sin información adicional registrada.</p>'}</div>`}
function openP(id){const p=P.find(x=>x.id===id);modal.innerHTML=`<div class="modal" onclick="if(event.target===this)closeM()"><div class="box"><button class="close" onclick="closeM()">×</button><div class="eyebrow">${esc(p.k)} · ${esc(p.loc)}</div><h2>${esc(p.n)}</h2><div class="badges"><span class="badge">${esc(p.s)}</span><span class="badge ${p.pr==='Crítica'?'hot':''}">${esc(p.pr)}</span><span class="badge">${esc(p.date)}</span></div><div class="docbar"><button class="ghost" onclick="downloadMd('${p.id}')">↓ DESCARGAR .MD</button><button class="primary" onclick="downloadPdf('${p.id}')">↓ DESCARGAR PDF</button></div><div class="modalgrid"><div class="panel"><span>SITUACIÓN</span><p>${esc(p.d)}</p></div><div class="panel"><span>PRÓXIMO MOVIMIENTO</span><p>${esc(p.next)}</p></div>${listPanel('COMERCIAL / PRECIO',p.commercial)}${listPanel('RESPONSABLES',p.owners)}${listPanel('RIESGOS',p.risks)}${listPanel('PENDIENTES',p.pending)}${listPanel('NOTAS',p.notes)}</div>${p.links?.length?`<div class="links">${p.links.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener">${esc(x[0])} ↗</a>`).join('')}</div>`:''}</div></div>`}
function closeM(){modal.innerHTML=''}
const tabsEl=document.getElementById('tabs'),view=document.getElementById('view'),modal=document.getElementById('modal');
function render(){nav();view.innerHTML=tab==='summary'?summary():tab==='projects'?projects():tab==='calendar'?calendar():audit()}
render();