// RR Aliados — Finance UI V11
// Installment simulator + actionable audit + readable commercial cockpit.
(function(){
'use strict';
const BUILD='V11', OPENING=2620000, ASOF='2026-08-21';
const TERMS=[4,6,12,18,24,30];
const PROJECTS=[['wundeer','Wundeer'],['boga','BOGA'],['satiro','Sátiro Sushi'],['zapatos','Zapatos'],['harbin','Harbin'],['candilejas','Candilejas'],['labanca','La Banca'],['carreta','La Carreta'],['marytierra','Mar y Tierra'],['charles','Charles Brown'],['plazoleta','Plazoleta Jardín'],['amsterdam','Amsterdam ×3'],['globos','Globos'],['junisama','Junisama / BOGA legado']];
const NAME=Object.fromEntries(PROJECTS);
const FINANCED={
 harbin:{name:'Harbin',base:30000000,early:6000000,totalCost:8000000},
 candilejas:{name:'Candilejas',base:20000000,early:4000000,totalCost:7000000},
 labanca:{name:'La Banca',base:20000000,early:4000000,totalCost:7000000},
 carreta:{name:'La Carreta',base:12000000,early:4000000,totalCost:6000000},
 plazoleta:{name:'Plazoleta Jardín · 8 restaurantes',base:72000000,early:7500000,totalCost:12000000}
};
const TABS=[['summary','Resumen'],['runway','Runway / Flujo'],['pnl','P&L'],['projects','Proyectos'],['commercial11','Comercial'],['costs','Costos'],['accounting11','Contabilidad'],['calendar','Calendario'],['audit11','Auditoría']];
const state=window.RR_V11_STATE||{tab:'summary',projects:['wundeer','boga','satiro'],includeOverhead:true,scenario:'base',pnlMonth:'2026-09',terms:{harbin:30,candilejas:30,labanca:30,carreta:30,plazoleta:30}};
window.RR_V11_STATE=state;
const money=n=>(n<0?'-':'')+'$'+Math.abs(Math.round(n||0)).toLocaleString('es-CO');
const pct=n=>Number.isFinite(n)?(n*100).toLocaleString('es-CO',{maximumFractionDigits:1})+'%':'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=s=>new Date(s+'T12:00:00').toLocaleDateString('es-CO',{day:'2-digit',month:'short',year:'numeric'});
const monthLabel=s=>{const [y,m]=s.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('es-CO',{month:'short',year:'numeric'}).replace('.','')};
const addMonths=(s,n)=>{const d=new Date(s+'T12:00:00');d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)};
const lastDay=(y,m)=>String(new Date(y,m,0).getDate()).padStart(2,'0');
const discount=t=>0.15*((30-t)/26);
const plan=(id,t=state.terms[id]||30)=>{const x=FINANCED[id];if(!x)return null;const d=discount(t),total=Math.round(x.base*(1-d)),installment=Math.round(total/t);return{...x,term:t,discount:d,total,installment,cash6:installment*Math.min(t,6),gross:total-x.totalCost,grossMargin:total?(total-x.totalCost)/total:0}};
const ev=(date,project,amount,kind,status,note)=>({date,project,amount,kind,status,note});
function modelEvents(termOverride={}){
 const a=[];
 a.push(ev('2026-08-30','overhead',750000,'expense','committed','Manuel $350K + Samuel $250K + IA $100K + hosting $50K'));
 for(let i=0;i<18;i++){const d=new Date(2026,8+i,15,12),y=d.getFullYear(),m=d.getMonth()+1,mm=String(m).padStart(2,'0');a.push(ev(`${y}-${mm}-15`,'overhead',900000,'expense','committed','Operación RR · quincena'));a.push(ev(`${y}-${mm}-${lastDay(y,m)}`,'overhead',900000,'expense','committed','Operación RR · quincena'));}
 a.push(ev('2026-08-30','wundeer',2166000,'expense','committed','Mes 1 · segunda mitad'));
 a.push(ev('2026-09-15','wundeer',1071000,'expense','committed','Mes 2 · primera mitad'));
 a.push(ev('2026-09-30','wundeer',1071000,'expense','committed','Mes 2 · segunda mitad'));
 a.push(ev('2026-10-15','wundeer',9000000,'income','confirmed','Cobro retroactivo · 2 meses iniciales'));
 ['2026-10','2026-11','2026-12','2027-01'].forEach(mon=>{const [y,m]=mon.split('-').map(Number);a.push(ev(mon+'-15','wundeer',1071000,'expense','conditional','Costo de continuidad'));a.push(ev(mon+'-'+lastDay(y,m),'wundeer',1071000,'expense','conditional','Costo de continuidad'));});
 ['2026-11-15','2026-12-15','2027-01-15','2027-02-15'].forEach((d,i)=>a.push(ev(d,'wundeer',4500000,'income','conditional',`Continuidad · cuota ${i+3}/6`)));
 a.push(ev('2026-09-01','boga',1200000,'income','confirmed','Pago desarrollo'));
 for(let i=0;i<30;i++)a.push(ev(addMonths('2026-09-01',i),'satiro',400000,'income','confirmed',`Cuota ${i+1}/30`));
 ['2026-09-15','2026-09-30','2026-10-15','2026-10-30'].forEach(d=>a.push(ev(d,'satiro',1000000,'expense','committed','Ejecución primeros 2 meses')));
 ['2026-09-15','2026-09-30'].forEach(d=>a.push(ev(d,'zapatos',2166000,'expense','provisional','Mes 1 provisional')));a.push(ev('2026-11-15','zapatos',9000000,'income','provisional','Cobro retroactivo estimado'));
 Object.keys(FINANCED).forEach(id=>{const x=FINANCED[id],t=termOverride[id]||state.terms[id]||30,p=plan(id,t);['2026-09-15','2026-09-30','2026-10-15','2026-10-30'].forEach(d=>a.push(ev(d,id,x.early/4,'expense','estimated','Costo de arranque')));for(let i=0;i<t;i++)a.push(ev(addMonths('2026-10-15',i),id,p.installment,'income','estimated',`Cuota ${i+1}/${t} · descuento ${pct(p.discount)}`));});
 ['marytierra','charles'].forEach(id=>['2026-09-15','2026-09-30','2026-10-15','2026-10-30'].forEach(d=>a.push(ev(d,id,1000000,'expense','estimated','Costo de arranque · precio pendiente'))));
 a.push(ev('2026-10-30','amsterdam',15000000,'income','estimated','3 desarrollos × $5M contra entrega'));a.push(ev('2026-11-30','amsterdam',1500000,'expense','conditional','Comisión máxima Aleja · falta definir si va dentro o fuera del costo'));
 ['2026-10-15','2026-10-30','2026-11-15','2026-11-30'].forEach(d=>a.push(ev(d,'globos',200000,'expense','estimated','Costo inicial')));a.push(ev('2026-11-15','globos',2000000,'income','estimated','Desarrollo contra entrega'));
 ['2026-11-15','2026-12-15','2027-01-15','2027-02-15'].forEach((d,i)=>{a.push(ev(d,'junisama',5000000,'income','estimated',`Licitación ${i+1}/4 · bono 1,5% no cuantificado`));a.push(ev(d,'junisama',2000000,'expense','estimated',`Pago ${i+1}/4 a David`));});
 return a.sort((x,y)=>x.date.localeCompare(y.date));
}
function includeStatus(s,scenario=state.scenario){if(scenario==='committed')return s==='confirmed'||s==='committed';if(scenario==='base')return s!=='conditional'&&s!=='provisional';return true;}
function eventsFor(ids=state.projects,scenario=state.scenario,termOverride={}){const set=new Set(ids);return modelEvents(termOverride).filter(x=>includeStatus(x.status,scenario)&&(x.project==='overhead'?state.includeOverhead:set.has(x.project)));}
function calculate(events){let balance=OPENING,min=OPENING,minDate=ASOF,firstNegative=null,income=0,expense=0;const byDate={};events.forEach(x=>(byDate[x.date]??=[]).push(x));const rows=Object.keys(byDate).sort().map(date=>{const items=byDate[date],inc=items.filter(x=>x.kind==='income').reduce((a,x)=>a+x.amount,0),exp=items.filter(x=>x.kind==='expense').reduce((a,x)=>a+x.amount,0),net=inc-exp;income+=inc;expense+=exp;balance+=net;if(balance<0&&!firstNegative)firstNegative=date;if(balance<min){min=balance;minDate=date}return{date,items,income:inc,expense:exp,net,balance};});return{rows,income,expense,ending:balance,min,minDate,firstNegative,need:Math.max(0,-min)};}
function totals(events){const m={};events.forEach(x=>{if(!m[x.project])m[x.project]={project:x.project,income:0,expense:0};m[x.project][x.kind]+=x.amount;});return Object.values(m).map(x=>({...x,net:x.income-x.expense}));}
function projectSelector(){return `<section class="v11Controls"><div class="v11ControlTop"><div><b>Escenario de caja</b><small>Selecciona proyectos y nivel de certeza. Los plazos de los proyectos financiados se controlan debajo.</small></div><div><button onclick="RRV11.all(true)">Todos</button><button onclick="RRV11.all(false)">Ninguno</button></div></div><div class="v11Checks">${PROJECTS.map(([id,n])=>`<label class="${state.projects.includes(id)?'on':''}"><input type="checkbox" ${state.projects.includes(id)?'checked':''} onchange="RRV11.toggle('${id}')"><span>${esc(n)}</span></label>`).join('')}</div><div class="v11Options"><label><input type="checkbox" ${state.includeOverhead?'checked':''} onchange="RRV11.overhead(this.checked)"> Incluir gastos fijos RR</label><label>Nivel de certeza <select onchange="RRV11.scenario(this.value)"><option value="committed" ${state.scenario==='committed'?'selected':''}>Confirmado / comprometido</option><option value="base" ${state.scenario==='base'?'selected':''}>Base: incluye estimados</option><option value="all" ${state.scenario==='all'?'selected':''}>Todo: condicional + provisional</option></select></label></div></section>`;}
function termSimulator(){return `<div class="sectionHead"><div><h2>Simulador de cuotas y liquidez</h2><p class="sectionIntro">Cada proyecto puede usar un plazo distinto. Cambiar una cuota modifica el precio final por descuento, el pago mensual y el Runway completo.</p></div></div><div class="v11TermActions"><span>Aplicar un mismo plazo a todos:</span>${TERMS.map(t=>`<button onclick="RRV11.allTerms(${t})">${t} cuotas</button>`).join('')}</div><div class="v11TermGrid">${Object.keys(FINANCED).map(id=>{const p=plan(id);return `<article class="v11TermCard"><div class="v11TermHead"><div><b>${esc(p.name)}</b><small>Base ${money(p.base)}</small></div><select onchange="RRV11.term('${id}',+this.value)">${TERMS.map(t=>`<option value="${t}" ${p.term===t?'selected':''}>${t} cuotas</option>`).join('')}</select></div><div class="v11TermStats"><span><small>Descuento</small><b>${pct(p.discount)}</b></span><span><small>Precio final</small><b>${money(p.total)}</b></span><span><small>Cuota mensual</small><b>${money(p.installment)}</b></span><span><small>Cobro 6 meses</small><b>${money(p.cash6)}</b></span><span><small>Margen bruto estimado</small><b>${money(p.gross)}</b></span><span><small>Margen %</small><b>${pct(p.grossMargin)}</b></span></div></article>`;}).join('')}</div>`;}
function comparisonMatrix(){const baseline=['wundeer','boga','satiro'];return `<div class="sectionHead"><div><h2>¿Qué plazo da más liquidez?</h2><p class="sectionIntro">Cada celda calcula el escenario base de RR + ese proyecto, manteniendo sus costos de arranque. “Brecha” es el máximo capital de trabajo que necesitarías antes de recuperar caja.</p></div></div><div class="desktopTableWrap"><table class="dataTable v11Compare"><thead><tr><th>Proyecto</th>${TERMS.map(t=>`<th>${t} cuotas</th>`).join('')}</tr></thead><tbody>${Object.keys(FINANCED).map(id=>`<tr><td><b>${esc(FINANCED[id].name)}</b></td>${TERMS.map(t=>{const c=calculate(eventsFor([...baseline,id],'base',{[id]:t})),p=plan(id,t);return `<td class="${c.need===0?'goodCell':''}"><b>${money(p.installment)}/mes</b><small>Precio ${money(p.total)}<br>Brecha ${money(c.need)}<br>6m ${money(p.cash6)}</small></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function runway(){const events=eventsFor(),c=calculate(events),tt=totals(events),recommended=Math.ceil(c.need*1.15/100000)*100000,drivers=tt.filter(x=>x.expense>0).sort((a,b)=>b.expense-a.expense).slice(0,6);return `<div class="sectionHead"><div><h2>Runway / Flujo</h2><p class="sectionIntro">Aquí evalúas liquidez, no utilidad: cuándo falta caja, cuánto capital de trabajo requiere cada combinación y qué proyectos provocan la brecha.</p></div></div>${projectSelector()}${termSimulator()}<section class="v11Hero"><div><span>CAJA HOY</span><b>${money(OPENING)}</b></div><div><span>INGRESOS ESCENARIO</span><b>${money(c.income)}</b></div><div><span>GASTOS ESCENARIO</span><b>${money(c.expense)}</b></div><div class="${c.need?'danger':''}"><span>BRECHA MÁXIMA</span><b>${money(c.need)}</b><small>${c.need?dateLabel(c.minDate):'sin déficit'}</small></div><div><span>LÍNEA SUGERIDA</span><b>${money(recommended)}</b><small>brecha + 15%</small></div></section><div class="v11Explain ${c.need?'bad':'good'}"><b>${c.need?'La combinación seleccionada necesita capital de trabajo.':'La combinación seleccionada no entra en déficit.'}</b><p>${c.need?`La caja cruza a negativo el <strong>${dateLabel(c.firstNegative)}</strong>. El peor punto ocurre el <strong>${dateLabel(c.minDate)}</strong>, cuando faltan <strong>${money(c.need)}</strong>. Esto no es una pérdida: es dinero temporal para financiar ejecución antes de los cobros. Una línea prudente sería <strong>${money(recommended)}</strong>.`:'Con estos proyectos, plazos y nivel de certeza, la caja no baja de cero.'}</p>${drivers.length?`<div class="v11Drivers">${drivers.map(x=>`<span><b>${x.project==='overhead'?'Operación RR':esc(NAME[x.project]||x.project)}</b>${money(x.expense)} de salidas</span>`).join('')}</div>`:''}</div>${comparisonMatrix()}<div class="sectionHead"><div><h2>Detalle cronológico</h2><p class="sectionIntro">Las filas rojas indican días en los que el saldo acumulado está por debajo de cero.</p></div></div><div class="desktopTableWrap"><table class="dataTable v11Runway"><thead><tr><th>Fecha</th><th>Qué ocurre</th><th>Entradas</th><th>Salidas</th><th>Neto</th><th>Saldo</th><th>Brecha</th></tr></thead><tbody>${c.rows.map(r=>`<tr class="${r.balance<0?'dangerRow':''}"><td><b>${dateLabel(r.date)}</b></td><td>${r.items.map(x=>`${esc(x.project==='overhead'?'Operación RR':NAME[x.project]||x.project)} · ${esc(x.note)}`).join('<br>')}</td><td class="plus">${r.income?money(r.income):'—'}</td><td class="minus">${r.expense?money(r.expense):'—'}</td><td>${money(r.net)}</td><td><b>${money(r.balance)}</b></td><td class="${r.balance<0?'minus':''}">${r.balance<0?money(Math.abs(r.balance)):'—'}</td></tr>`).join('')}</tbody></table></div>`;}
const MONTHS=['2026-08','2026-09','2026-10','2026-11','2026-12','2027-01','2027-02','2027-03'];
function pnlData(m){const e=eventsFor().filter(x=>x.date.slice(0,7)===m),revenue=e.filter(x=>x.kind==='income').reduce((a,x)=>a+x.amount,0),direct=e.filter(x=>x.kind==='expense'&&x.project!=='overhead').reduce((a,x)=>a+x.amount,0),overhead=e.filter(x=>x.kind==='expense'&&x.project==='overhead').reduce((a,x)=>a+x.amount,0),gross=revenue-direct,operating=gross-overhead;return{e,revenue,direct,overhead,gross,operating,grossMargin:revenue?gross/revenue:null,operatingMargin:revenue?operating/revenue:null};}
function pnl(){const x=pnlData(state.pnlMonth),map={};x.e.filter(e=>e.project!=='overhead').forEach(e=>{if(!map[e.project])map[e.project]={project:e.project,revenue:0,direct:0};if(e.kind==='income')map[e.project].revenue+=e.amount;else map[e.project].direct+=e.amount;});return `<div class="sectionHead"><div><h2>P&L gerencial</h2><p class="sectionIntro">Runway responde “¿hay caja?”; P&L responde “¿la operación deja margen?”. Cambia con los mismos proyectos y plazos elegidos en Runway.</p></div></div><div class="v11Warning"><b>No es utilidad contable oficial.</b><span>Faltan impuestos, fee del contador, transporte/reuniones y costeo interno por horas.</span></div><div class="v11MonthPicker">${MONTHS.map(m=>`<button class="${state.pnlMonth===m?'on':''}" onclick="RRV11.month('${m}')">${monthLabel(m)}</button>`).join('')}</div><section class="v11Hero"><div><span>INGRESOS</span><b>${money(x.revenue)}</b></div><div><span>COSTO DIRECTO</span><b>${money(x.direct)}</b></div><div><span>MARGEN BRUTO</span><b>${money(x.gross)}</b><small>${pct(x.grossMargin)}</small></div><div><span>OVERHEAD RR</span><b>${money(x.overhead)}</b></div><div class="${x.operating<0?'danger':''}"><span>RESULTADO OPERATIVO</span><b>${money(x.operating)}</b><small>${pct(x.operatingMargin)}</small></div></section><div class="v11Explain ${x.operating<0?'bad':'good'}"><b>${x.operating<0?'Este mes no cubre todavía la estructura conocida.':'Este mes cubre la estructura conocida.'}</b><p>${x.revenue?`Por cada $100 de ingreso, quedan ${pct(x.grossMargin)} después de costos directos y ${pct(x.operatingMargin)} después del overhead conocido.`:'No hay ingreso suficiente en el mes para interpretar porcentajes de margen.'}</p></div><div class="desktopTableWrap"><table class="dataTable"><thead><tr><th>Proyecto</th><th>Ingresos</th><th>Costo directo</th><th>Contribución</th><th>Margen</th></tr></thead><tbody>${Object.values(map).map(r=>{const c=r.revenue-r.direct;return `<tr><td><b>${esc(NAME[r.project]||r.project)}</b></td><td>${money(r.revenue)}</td><td>${money(r.direct)}</td><td class="${c>=0?'plus':'minus'}">${money(c)}</td><td>${r.revenue?pct(c/r.revenue):'—'}</td></tr>`;}).join('')}</tbody></table></div>`;}
function commercial(){const cards=(window.P||[]).map(p=>{const f=FINANCED[p.id],pl=f?plan(p.id):null,price=pl?money(pl.base):(p.v||p.p?money(p.v||p.p):'Por confirmar');const isProspect=(p.k||'').toLowerCase().includes('prospect');return `<article class="commercialCard ${isProspect?'prospect':'client'}"><div class="commercialTop"><div><small>${esc(p.k||'Proyecto')}</small><h3>${esc(p.n)}</h3></div><span class="commercialPriority">${esc(p.pr||'—')}</span></div><div class="commercialMeta"><span><small>Estado</small><b>${esc(p.s||'—')}</b></span><span><small>Fecha / hito</small><b>${esc(p.date||'—')}</b></span><span><small>Valor base</small><b>${price}</b></span>${pl?`<span><small>Plan evaluado</small><b>${pl.term} cuotas · ${money(pl.installment)}/mes</b></span>`:''}</div><div class="commercialNext"><small>SIGUIENTE PASO</small><p>${esc(p.next||'Sin siguiente paso definido.')}</p></div>${p.commercial?.length?`<div class="commercialBlock"><small>CONDICIONES COMERCIALES</small>${p.commercial.map(x=>`<span>• ${esc(x)}</span>`).join('')}</div>`:''}${p.risks?.length?`<div class="commercialBlock risks"><small>RIESGOS</small>${p.risks.slice(0,3).map(x=>`<span>• ${esc(x)}</span>`).join('')}</div>`:''}</article>`;}).join('');return `<div class="sectionHead"><div><h2>Comercial</h2><p class="sectionIntro">Una ficha por oportunidad para ver estado, precio, condiciones, próximo paso y riesgo sin comprimir todo en una tabla.</p></div></div><section class="commercialSummary"><div><span>OPORTUNIDADES</span><b>${(window.P||[]).filter(p=>(p.k||'').toLowerCase().includes('prospect')).length}</b></div><div><span>CLIENTES / ACTIVOS</span><b>${(window.P||[]).filter(p=>!(p.k||'').toLowerCase().includes('prospect')).length}</b></div><div><span>PRECIOS PENDIENTES</span><b>2</b><small>Mar y Tierra · Charles Brown</small></div></section><div class="commercialGrid">${cards}</div>`;}
function accounting(){const committed=calculate(eventsFor(['wundeer','boga','satiro'],'committed'));return `<div class="sectionHead"><div><h2>Contabilidad y control financiero</h2><p class="sectionIntro">Esta sección distingue caja real, obligaciones, exposición y datos que faltan para convertir el tablero en contabilidad formal.</p></div></div><section class="v11Hero"><div><span>CAJA DISPONIBLE</span><b>${money(OPENING)}</b><small>corte 21 ago</small></div><div><span>GASTO FIJO / MES</span><b>${money(1800000)}</b></div><div><span>CXC CERCANA</span><b>${money(1200000)}</b><small>BOGA · 1 sep</small></div><div><span>CXP CONOCIDA</span><b>${money(350000)}</b><small>Manuel · 30 ago</small></div><div class="${committed.need?'danger':''}"><span>CAPITAL DE TRABAJO COMPROMETIDO</span><b>${money(committed.need)}</b><small>${committed.need?dateLabel(committed.minDate):'sin brecha'}</small></div></section><div class="v11AccountingGrid"><article><b>Obligaciones recurrentes</b><p>Manuel $500K/quincena, Samuel $250K, IA $100K, hosting $50K. Agosto 30 tiene la excepción de Manuel por $350K pendiente.</p></article><article><b>Causación vs caja</b><p>El tablero sigue siendo principalmente caja. Para un P&L contable faltará definir cuándo se reconoce cada ingreso y gasto, no solo cuándo se paga.</p></article><article><b>Impuestos y contador</b><p>Faltan fee del contador, calendario tributario, retenciones y provisión de impuestos. Sin esto no debe llamarse “utilidad neta”.</p></article><article><b>Costeo interno</b><p>Manuel y Santiago todavía no se imputan a proyectos. Hace falta horas × tarifa interna para conocer rentabilidad real por cliente.</p></article><article><b>Conciliación bancaria</b><p>La caja de $2,62M debe conciliarse semanalmente contra banco. Los saldos históricos del Excel no deben reemplazar esta cifra.</p></article><article><b>Variables no presupuestadas</b><p>Transporte, reuniones y otros gastos esporádicos aún no tienen presupuesto recurrente.</p></article></div>`;}
function audit(){const committed=calculate(eventsFor(['wundeer','boga','satiro'],'committed'));const base=calculate(eventsFor(state.projects,'base'));const shiftW=(days)=>{const e=eventsFor(['wundeer','boga','satiro'],'committed').map(x=>x.project==='wundeer'&&x.kind==='income'&&x.amount===9000000?{...x,date:addMonths(x.date,0)}:x);const target=e.find(x=>x.project==='wundeer'&&x.amount===9000000&&x.kind==='income');if(target){const d=new Date(target.date+'T12:00:00');d.setDate(d.getDate()+days);target.date=d.toISOString().slice(0,10);}return calculate(e.sort((a,b)=>a.date.localeCompare(b.date)));};const s15=shiftW(15),s30=shiftW(30);const issues=[
 {level:'critical',title:'Liquidez inmediata',finding:committed.need?`La operación comprometida necesita hasta ${money(committed.need)} de capital de trabajo y toca su peor punto el ${dateLabel(committed.minDate)}.`:'La operación comprometida no entra en déficit con los datos actuales.',impact:'Si el capital no está disponible antes de la fecha crítica, RR puede incumplir pagos aun teniendo proyectos rentables.',action:committed.need?`Asegurar una línea mínima de ${money(committed.need)}; objetivo prudente ${money(Math.ceil(committed.need*1.15/100000)*100000)}.`:'Mantener un colchón equivalente a por lo menos una quincena de operación.'},
 {level:'critical',title:'Dependencia de Wundeer',finding:`Si el cobro de $9M se mueve 15 días, la brecha máxima sería ${money(s15.need)}; con 30 días, ${money(s30.need)}.`,impact:'Un solo cobro concentra una parte importante de la recuperación de caja.',action:'Confirmar por escrito fecha de pago, responsable y plan de contingencia antes de financiar más arranques.'},
 {level:'high',title:'Crecimiento financiado por RR',finding:`El escenario que tienes seleccionado puede requerir hasta ${money(base.need)} antes de recuperar caja.`,impact:'Cerrar más proyectos puede empeorar liquidez aunque aumente utilidad contractual.',action:'Usar el simulador de cuotas como gate: ningún cierre debería arrancar sin conocer su brecha incremental y fuente de capital.'},
 {level:'high',title:'Utilidad todavía incompleta',finding:'El P&L gerencial no incluye impuestos, contador, transporte/reuniones ni costo interno por horas.',impact:'El margen mostrado puede sobreestimar la utilidad real.',action:'Crear costo hora interno y provisión tributaria antes de usar “utilidad neta” como KPI.'},
 {level:'medium',title:'Datos comerciales incompletos',finding:'Mar y Tierra y Charles Brown no tienen precio base confirmado. Plazoleta solo tiene regla clara para 8 restaurantes.',impact:'No se puede calcular margen ni necesidad de caja confiable para todas las combinaciones.',action:'Cerrar precios de Mar y Tierra/Charles y definir descuento Plazoleta para 1–7 restaurantes.'},
 {level:'medium',title:'Amsterdam',finding:'La comisión máxima de Aleja de $500K por proyecto sigue sin aclararse si está incluida o adicional a los $2M de costo esperado por proyecto.',impact:'Puede mover el margen total hasta $1,5M.',action:'Definir tratamiento antes de calcular utilidad final de Amsterdam.'},
 {level:'medium',title:'Candilejas / La Banca',finding:'Persisten notas antiguas sobre $18M en 4 meses y un incentivo de $1M, mientras el modelo nuevo usa descuentos por número de cuotas.',impact:'Riesgo de cotizar con dos reglas comerciales incompatibles.',action:'Declarar explícitamente cuál política reemplaza a cuál y eliminar la regla vieja del material comercial.'},
 {level:'medium',title:'Pipeline sin probabilidad',finding:'Los prospectos tienen fechas y precios, pero no una probabilidad de cierre homogénea.',impact:'La proyección “base” no es un forecast estadístico; es un escenario.',action:'Añadir probabilidad de cierre, fecha esperada y valor ponderado por oportunidad.'},
 {level:'medium',title:'Unit economics y retorno del capital',finding:'Ya podemos ver margen contractual, pero falta medir cuánto capital queda inmovilizado y cuántos días tarda en recuperarse por proyecto.',impact:'Dos proyectos con el mismo margen pueden tener riesgos de caja muy diferentes.',action:'Añadir ROI sobre capital de trabajo y payback por proyecto como próximo KPI.'}
];return `<div class="sectionHead"><div><h2>Auditoría financiera accionable</h2><p class="sectionIntro">No es una lista genérica: cada hallazgo explica qué observamos, por qué importa y qué decisión debes tomar.</p></div></div><section class="auditScore"><div><span>BRECHA COMPROMETIDA</span><b>${money(committed.need)}</b></div><div><span>STRESS WUNDEER +15D</span><b>${money(s15.need)}</b></div><div><span>STRESS WUNDEER +30D</span><b>${money(s30.need)}</b></div><div><span>BRECHA ESCENARIO ACTUAL</span><b>${money(base.need)}</b></div></section><div class="auditRoadmap">${issues.map((x,i)=>`<article class="auditFinding ${x.level}"><div class="auditNum">${String(i+1).padStart(2,'0')}</div><div><div class="auditTitle"><b>${esc(x.title)}</b><span>${x.level==='critical'?'CRÍTICO':x.level==='high'?'ALTO':'A REVISAR'}</span></div><dl><div><dt>Hallazgo</dt><dd>${esc(x.finding)}</dd></div><div><dt>Impacto</dt><dd>${esc(x.impact)}</dd></div><div><dt>Decisión / acción</dt><dd>${esc(x.action)}</dd></div></dl></div></article>`).join('')}</div><div class="sectionHead"><div><h2>Orden recomendado de trabajo</h2></div></div><div class="auditNext"><article><b>Ahora · 0–7 días</b><p>Confirmar Wundeer, asegurar capacidad de caja para septiembre, cerrar contador/impuestos y resolver Amsterdam.</p></article><article><b>Antes del próximo cierre</b><p>Usar el simulador de cuotas, definir fuente de capital y eliminar políticas comerciales contradictorias.</p></article><article><b>Durante septiembre</b><p>Costear horas internas, añadir probabilidades al pipeline y construir P&L contable con provisión fiscal.</p></article><article><b>Mensualmente</b><p>Conciliación bancaria, revisión de runway 13 semanas, margen por proyecto y retorno sobre capital de trabajo.</p></article></div>`;}
const legacy={summary:typeof summary==='function'?summary:null,projects:typeof projects==='function'?projects:null,costs:typeof costs==='function'?costs:null,calendar:typeof calendar==='function'?calendar:null};
function safeLegacy(k){try{return legacy[k]?legacy[k]():`<div class="empty">Sección ${esc(k)} no disponible.</div>`;}catch(err){return `<div class="v11Error"><b>Error en ${esc(k)}</b><p>${esc(err.message||err)}</p></div>`;}}
function view(id){if(id==='runway')return runway();if(id==='pnl')return pnl();if(id==='commercial11')return commercial();if(id==='accounting11')return accounting();if(id==='audit11')return audit();return safeLegacy(id);}
function render11(){const tabs=document.getElementById('tabs');if(tabs)tabs.innerHTML=TABS.map(([id,label])=>`<button type="button" class="${state.tab===id?'on':''}" onclick="RRV11.tab('${id}')">${label}</button>`).join('');const el=document.getElementById('view');if(el){try{el.innerHTML=view(state.tab);}catch(err){el.innerHTML=`<div class="v11Error"><b>Error de render en ${esc(state.tab)}</b><p>${esc(err.stack||err.message||err)}</p></div>`;}}document.documentElement.dataset.rrBuild='v11';const f=document.querySelector('footer');if(f){f.querySelectorAll('.buildMark').forEach(x=>x.remove());f.insertAdjacentHTML('beforeend',' <span class="buildMark">· UI V11</span>');}}
window.RRV11={tab:id=>{state.tab=id;render11();},toggle:id=>{const i=state.projects.indexOf(id);if(i>=0)state.projects.splice(i,1);else state.projects.push(id);render11();},all:on=>{state.projects=on?PROJECTS.map(x=>x[0]):[];render11();},overhead:on=>{state.includeOverhead=on;render11();},scenario:v=>{state.scenario=v;render11();},month:v=>{state.pnlMonth=v;render11();},term:(id,t)=>{state.terms[id]=t;if(!state.projects.includes(id))state.projects.push(id);render11();},allTerms:t=>{Object.keys(FINANCED).forEach(id=>state.terms[id]=t);Object.keys(FINANCED).forEach(id=>{if(!state.projects.includes(id))state.projects.push(id);});render11();},render:render11};
window.render=render11;window.nav=()=>render11();render11();
})();