// RR Aliados — financial model v2
// Separates project value, projected cash collection, and commercial risk weighting.
const FIN={
  wundeer:{total:27000000,cash2:9000000,cash6:27000000,prob:null,weighted:null,n:'6 cuotas de $4.5M. Los primeros 2 meses ($9M) se pagan el 15 de octubre. Si el cliente continúa, la tercera cuota de $4.5M se paga el 15 de noviembre y el contrato contempla 6 cuotas en total. El recaudo a 6 meses es potencial y depende de continuidad después del bloque inicial.'},
  boga:{total:3000000,cash2:1200000,cash6:3000000,prob:null,weighted:null,n:'$1.2M de desarrollo se paga antes del 1 de septiembre. Además se evalúan 6 meses de mantenimiento a $300K/mes = $1.8M. Total económico evaluado: $3M.'},
  satiro:{total:12000000,cash2:null,cash6:null,prob:null,weighted:null,n:'Valor total definido. El calendario de recaudo no está documentado en esta sesión.'},
  harbin:{total:30000000,cash2:2000000,cash6:6000000,prob:.65,weighted:19500000,n:'30 cuotas de $1M desde la firma. Recaudo 2M/6M mostrado como escenario si firma y arranca inmediatamente. El total real sigue siendo $30M; $19.5M es solo valor ponderado por riesgo de cierre.'},
  zapatos:{total:null,cash2:null,cash6:null,prob:.50,weighted:null,n:'Discovery y cotización aún pendientes; no hay valor total definido.'},
  candilejas:{total:20000000,cash2:null,cash6:null,prob:.85,weighted:17000000,n:'Precio estándar: $20M. Alternativa pronto pago: $18M en 4 meses. Sin modalidad elegida no se fija recaudo 2M/6M. El valor ponderado no cambia el precio real.'},
  labanca:{total:20000000,cash2:null,cash6:null,prob:.85,weighted:17000000,n:'Precio estándar: $20M. Alternativa pronto pago: $18M en 4 meses. Sin modalidad elegida no se fija recaudo 2M/6M. El valor ponderado no cambia el precio real.'},
  marytierra:{total:12000000,cash2:null,cash6:null,prob:.80,weighted:9600000,n:'Valor total definido en $12M. Calendario de recaudo no documentado aún.'},
  carreta:{total:12000000,cash2:null,cash6:null,prob:.80,weighted:9600000,n:'Valor total definido en $12M. Calendario de recaudo no documentado aún.'},
  charles:{total:12000000,cash2:null,cash6:null,prob:.78,weighted:9360000,n:'Valor total definido en $12M. Calendario de recaudo no documentado aún.'},
  plazoleta:{total:72000000,cash2:null,cash6:null,prob:.65,weighted:46800000,n:'8 restaurantes; 6 pagados y 2 gratis = $72M. Recaudo depende de modalidad aún no definida. Riesgo comercial mayor porque Andrés necesita aprobación de otros socios.'},
  amsterdam:{total:15000000,cash2:null,cash6:null,prob:.75,weighted:11250000,n:'Valor total de referencia: 3 proyectos × $5M = $15M. Calendario de recaudo no documentado.'},
  globos:{total:null,cash2:null,cash6:null,prob:.20,weighted:null,n:'Sin alcance, reunión ni valor definidos.'},
  junisama:{total:null,cash2:null,cash6:null,prob:.35,weighted:null,n:'Pendiente indicaciones finales antes de definir continuidad y valor.'}
};
for(const p of P){const f=FIN[p.id]||{total:p.v||p.p||null,cash2:null,cash6:null,prob:null,weighted:null,n:'Sin modelo financiero específico documentado.'};p.fin=f;p.totalValue=f.total;p.cash2=f.cash2;p.cash6=f.cash6;p.closeProb=f.prob;p.weighted=f.weighted;}
function val(v){return v==null?'POR DEFINIR':COP(v)}
function risk(v){return v==null?'—':Math.round(v*100)+'%'}
function money(p){return ['VALOR TOTAL',p.totalValue?COP(p.totalValue):'POR DEFINIR']}
function financeTotals(){return P.reduce((a,p)=>{if(p.totalValue)a.total+=p.totalValue;if(p.cash2)a.c2+=p.cash2;if(p.cash6)a.c6+=p.cash6;if(p.weighted)a.weighted+=p.weighted;return a},{total:0,c2:0,c6:0,weighted:0})}
function cards(list){return list.length?`<div class="grid">${list.map(p=>`<article class="card" onclick="openP('${p.id}')"><div class="kicker"><span>${esc(p.k)} · ${esc(p.loc)}</span><span>${esc(p.date)}</span></div><h3>${esc(p.n)}</h3><div class="badges"><span class="badge ${p.pr==='Crítica'?'hot':''}">${esc(p.pr)}</span><span class="badge">${esc(p.s)}</span>${p.closeProb!=null?`<span class="badge good">RIESGO ${risk(p.closeProb)}</span>`:''}</div><p>${esc(p.d)}</p><div class="next"><span>SIGUIENTE MOVIMIENTO</span>${esc(p.next)}</div><div class="pipeMini"><div><span>RECAUDO 2M</span><b>${val(p.cash2)}</b></div><div><span>RECAUDO 6M</span><b>${val(p.cash6)}</b></div><div><span>VALOR TOTAL</span><b>${val(p.totalValue)}</b></div></div></article>`).join('')}</div>`:'<div class="empty">No hay proyectos con este filtro.</div>'}
function summary(){const t=financeTotals(),critical=P.filter(p=>p.pr==='Crítica').length,sep=P.filter(p=>p.date.includes('1 sep')).length;return `<section class="metrics"><div class="metric"><span>VALOR TOTAL CONOCIDO</span><strong>${COP(t.total)}</strong><small>NO ES CAJA</small></div><div class="metric accent"><span>RECAUDO 2 MESES</span><strong>${COP(t.c2)}</strong><small>SOLO FECHAS / ESCENARIOS DOCUMENTADOS</small></div><div class="metric income"><span>RECAUDO 6 MESES</span><strong>${COP(t.c6)}</strong><small>INCLUYE CONTINUIDADES INDICADAS</small></div><div class="metric"><span>VALOR PONDERADO PROSPECTOS</span><strong>${COP(Math.round(t.weighted))}</strong><small>INDICADOR DE RIESGO, NO PRECIO</small></div><div class="metric"><span>PRIORIDAD CRÍTICA</span><strong>${critical}</strong><small>${sep} HITOS EL 1 SEP</small></div></section><div class="note" style="margin-top:14px"><b>Valor total</b> = precio o valor económico completo del proyecto. <b>Recaudo</b> = dinero que puede entrar en ese horizonte según condiciones conocidas. <b>Valor ponderado</b> = valor total × probabilidad estimada de cierre y solo sirve como indicador comercial de riesgo; nunca reemplaza el precio real.</div><div class="sectionHead"><div><div class="label">FOCO INMEDIATO</div><h2>PRÓXIMOS MOVIMIENTOS</h2></div></div>${cards(P.filter(p=>['wundeer','boga','candilejas','labanca','plazoleta','harbin'].includes(p.id)))}`}
function pipeline(){const t=financeTotals();return `<div class="sectionHead"><div><div class="label">LECTURA FINANCIERA + COMERCIAL</div><h2>TOTAL · RECAUDO · RIESGO</h2></div></div><div class="note">Esta vista separa tres preguntas distintas: cuánto vale el proyecto completo, cuánto dinero podría entrar en 2 y 6 meses, y cuál es el riesgo comercial de los prospectos. Si una fecha o modalidad de pago no quedó definida en la sesión, el recaudo aparece como POR DEFINIR en lugar de inventarse.</div><section class="metrics" style="margin-top:14px"><div class="metric"><span>VALOR TOTAL CONOCIDO</span><strong>${COP(t.total)}</strong><small>VALOR BRUTO REAL</small></div><div class="metric accent"><span>RECAUDO 2M CONOCIDO</span><strong>${COP(t.c2)}</strong><small>HORIZONTE 60 DÍAS</small></div><div class="metric income"><span>RECAUDO 6M CONOCIDO</span><strong>${COP(t.c6)}</strong><small>HORIZONTE 180 DÍAS</small></div><div class="metric"><span>PONDERADO PROSPECTOS</span><strong>${COP(Math.round(t.weighted))}</strong><small>NO ES EL TOTAL REAL</small></div><div class="metric"><span>SIN TOTAL DEFINIDO</span><strong>${P.filter(p=>!p.totalValue).length}</strong><small>FUERA DEL TOTAL BRUTO</small></div></section><div class="pipelineTable"><div class="pipeRow head"><span>PROYECTO</span><span>VALOR TOTAL</span><span>RECAUDO 2M</span><span>RECAUDO 6M</span><span>PROB. CIERRE</span><span>VALOR PONDERADO</span><span>LECTURA</span></div>${P.map(p=>`<div class="pipeRow" onclick="openP('${p.id}')"><span><b>${esc(p.n)}</b><small>${esc(p.s)}</small></span><span>${val(p.totalValue)}</span><span>${val(p.cash2)}</span><span>${val(p.cash6)}</span><span>${risk(p.closeProb)}</span><span>${p.weighted==null?'—':COP(p.weighted)}</span><span><small>${esc(p.fin.n)}</small></span></div>`).join('')}</div>`}
const openFinanceBase=openP;
openP=function(id){openFinanceBase(id);const p=P.find(x=>x.id===id),grid=document.querySelector('#modal .modalgrid');if(!p||!grid)return;const panel=document.createElement('div');panel.className='panel pipelinePanel';panel.innerHTML=`<span>FINANZAS DEL PROYECTO</span><div class="pipeStats"><div><small>VALOR TOTAL</small><b>${val(p.totalValue)}</b></div><div><small>RECAUDO 2 MESES</small><b>${val(p.cash2)}</b></div><div><small>RECAUDO 6 MESES</small><b>${val(p.cash6)}</b></div><div><small>VALOR PONDERADO ${p.closeProb!=null?'· '+risk(p.closeProb):''}</small><b>${p.weighted==null?'—':COP(p.weighted)}</b></div></div><p>${esc(p.fin.n)}</p>`;grid.prepend(panel);}
const oldMdProjectV2=mdProject;
mdProject=function(p){return `# ${p.n} — Contexto Maestro RR Aliados\n\n**Tipo:** ${p.k}\n**Estado:** ${p.s}\n**Prioridad:** ${p.pr}\n**Ubicación:** ${p.loc}\n**Próxima fecha:** ${p.date}\n\n## Finanzas\n- Valor total del proyecto: ${val(p.totalValue)}\n- Recaudo proyectado a 2 meses: ${val(p.cash2)}\n- Recaudo proyectado a 6 meses: ${val(p.cash6)}\n- Probabilidad de cierre: ${risk(p.closeProb)}\n- Valor ponderado comercial: ${p.weighted==null?'—':COP(p.weighted)}\n- Lectura: ${p.fin.n}\n\n## Situación actual\n${p.d}\n\n## Próximo movimiento\n${p.next}\n\n${arr('Comercial / precio',p.commercial)}${arr('Responsables',p.owners)}${arr('Riesgos',p.risks)}${arr('Pendientes',p.pending)}${arr('Notas',p.notes)}${p.links?.length?'## Enlaces\n'+p.links.map(x=>`- [${x[0]}](${x[1]})`).join('\n')+'\n\n':''}---\nActualizado desde la sesión RR Aliados del 21/08/2026.`}
const rrSummaryBase=typeof rrProjectSummary==='function'?rrProjectSummary:null;
if(rrSummaryBase){rrProjectSummary=function(doc,p,y){y=rrSummaryBase(doc,p,y);y=rrEnsure(doc,y,22,'Resumen ejecutivo');doc.setFont('helvetica','bold');doc.setFontSize(6.3);rrSet(doc,'orchid');doc.text('LECTURA FINANCIERA',18,y);y+=4;y=rrBullet(doc,`Valor total: ${val(p.totalValue)}`,19,y,173,'black');y=rrBullet(doc,`Recaudo 2M: ${val(p.cash2)} · Recaudo 6M: ${val(p.cash6)}`,19,y,173,'black');if(p.weighted!=null)y=rrBullet(doc,`Valor ponderado: ${COP(p.weighted)} (${risk(p.closeProb)} de cierre). No reemplaza el valor total.`,19,y,173,'black');return y+3}}
render();
