// RR Aliados — pipeline comercial por horizonte.
// Pipeline = valor comercial * probabilidad estimada de cierre/activación.
// No representa recaudo/caja; es una lectura comercial ponderada.
const PIPE={
  wundeer:{p2:1,p6:1,pt:1,n:'Cliente contratado / operación activa'},
  boga:{p2:1,p6:1,pt:1,n:'Cliente contratado / cierre de entrega'},
  satiro:{p2:1,p6:1,pt:1,n:'Cliente contratado / desarrollo activo'},
  harbin:{p2:.40,p6:.65,pt:.65,n:'Reunión aún pendiente; decisión depende exclusivamente de la dueña'},
  zapatos:{p2:.25,p6:.50,pt:.50,n:'Discovery aún pendiente; valor comercial todavía no definido'},
  candilejas:{p2:.75,p6:.85,pt:.85,n:'Prototipo + propuesta en presentación comercial inmediata'},
  labanca:{p2:.75,p6:.85,pt:.85,n:'Prototipo + propuesta en presentación comercial inmediata'},
  marytierra:{p2:.65,p6:.80,pt:.80,n:'Presentación comercial agendada con prototipo y propuesta'},
  carreta:{p2:.65,p6:.80,pt:.80,n:'Presentación comercial agendada; valor definido en $12M'},
  charles:{p2:.60,p6:.78,pt:.78,n:'Presentación agendada, pero el prototipo aún debe construirse'},
  plazoleta:{p2:.45,p6:.65,pt:.65,n:'Alto valor, pero cierre depende de aprobación de varios socios'},
  amsterdam:{p2:.60,p6:.75,pt:.75,n:'Prototipos avanzados; aprobación depende de presentación en Aruba'},
  globos:{p2:.10,p6:.20,pt:.20,n:'Sin reunión, alcance ni hito comercial definido'},
  junisama:{p2:.20,p6:.35,pt:.35,n:'Frente pendiente de indicaciones antes de definir continuidad'}
};
for(const p of P){const c=PIPE[p.id]||{p2:.1,p6:.2,pt:.2,n:'Probabilidad provisional'};p.pipe=c;p.totalValue=p.v||p.p||0;p.pipe2=p.totalValue*c.p2;p.pipe6=p.totalValue*c.p6;p.pipeT=p.totalValue*c.pt;}
if(!tabs.some(t=>t[0]==='pipeline')) tabs.splice(2,0,['pipeline','Pipeline']);
function pct(v){return Math.round(v*100)+'%'}
function pipeMoney(v){return v?COP(Math.round(v)):'—'}
function pipelineTotals(){return P.reduce((a,p)=>{a.gross+=p.totalValue||0;a.p2+=p.pipe2||0;a.p6+=p.pipe6||0;a.pt+=p.pipeT||0;return a},{gross:0,p2:0,p6:0,pt:0})}
function cards(list){return list.length?`<div class="grid">${list.map(p=>{const m=money(p);return `<article class="card" onclick="openP('${p.id}')"><div class="kicker"><span>${esc(p.k)} · ${esc(p.loc)}</span><span>${esc(p.date)}</span></div><h3>${esc(p.n)}</h3><div class="badges"><span class="badge ${p.pr==='Crítica'?'hot':''}">${esc(p.pr)}</span><span class="badge">${esc(p.s)}</span>${p.totalValue?`<span class="badge good">P6 ${pct(p.pipe.p6)}</span>`:''}</div><p>${esc(p.d)}</p><div class="next"><span>SIGUIENTE MOVIMIENTO</span>${esc(p.next)}</div><div class="pipeMini"><div><span>2 MESES</span><b>${pipeMoney(p.pipe2)}</b></div><div><span>6 MESES</span><b>${pipeMoney(p.pipe6)}</b></div><div><span>VALOR TOTAL</span><b>${p.totalValue?COP(p.totalValue):'POR DEFINIR'}</b></div></div></article>`}).join('')}</div>`:'<div class="empty">No hay proyectos con este filtro.</div>'}
function summary(){const t=pipelineTotals(),critical=P.filter(p=>p.pr==='Crítica').length,sep=P.filter(p=>p.date.includes('1 sep')).length;return `<section class="metrics"><div class="metric"><span>PROYECTOS REGISTRADOS</span><strong>${P.length}</strong><small>ACTUALIZADOS</small></div><div class="metric accent"><span>PIPELINE POND. · 2 MESES</span><strong>${COP(Math.round(t.p2))}</strong><small>VALOR × PROBABILIDAD</small></div><div class="metric income"><span>PIPELINE POND. · 6 MESES</span><strong>${COP(Math.round(t.p6))}</strong><small>VALOR × PROBABILIDAD</small></div><div class="metric"><span>VALOR BRUTO CONOCIDO</span><strong>${COP(t.gross)}</strong><small>CONTRATADO + OPORTUNIDADES</small></div><div class="metric"><span>PRIORIDAD CRÍTICA</span><strong>${critical}</strong><small>${sep} HITOS EL 1 SEP</small></div></section><div class="note" style="margin-top:14px">Pipeline ponderado = valor comercial × probabilidad estimada de cierre/activación. No equivale a recaudo ni flujo de caja.</div><div class="sectionHead"><div><div class="label">FOCO INMEDIATO</div><h2>PRÓXIMOS MOVIMIENTOS</h2></div></div>${cards(P.filter(p=>['wundeer','candilejas','labanca','satiro','plazoleta','harbin'].includes(p.id)))}`}
function pipeline(){const t=pipelineTotals();return `<div class="sectionHead"><div><div class="label">EVALUACIÓN COMERCIAL</div><h2>PIPELINE · 2M / 6M / TOTAL</h2></div></div><div class="note">La probabilidad se asigna por etapa real del proyecto: contratado = 100%; presentación comercial inmediata = alta; reunión pendiente = media-baja; sin movimiento = baja. En Plazoleta se descuenta riesgo adicional por aprobación de varios socios. Esta vista mide probabilidad comercial, no caja.</div><section class="metrics" style="margin-top:14px"><div class="metric accent"><span>2 MESES PONDERADO</span><strong>${COP(Math.round(t.p2))}</strong><small>HORIZONTE 60 DÍAS</small></div><div class="metric income"><span>6 MESES PONDERADO</span><strong>${COP(Math.round(t.p6))}</strong><small>HORIZONTE 180 DÍAS</small></div><div class="metric"><span>TOTAL PONDERADO</span><strong>${COP(Math.round(t.pt))}</strong><small>LECTURA DE CARTERA</small></div><div class="metric"><span>VALOR BRUTO</span><strong>${COP(t.gross)}</strong><small>SIN PONDERAR</small></div><div class="metric"><span>OPORTUNIDADES SIN VALOR</span><strong>${P.filter(p=>!p.totalValue).length}</strong><small>NO ENTRAN AL CÁLCULO</small></div></section><div class="pipelineTable"><div class="pipeRow head"><span>PROYECTO</span><span>VALOR TOTAL</span><span>PROB. 2M</span><span>PIPELINE 2M</span><span>PROB. 6M</span><span>PIPELINE 6M</span><span>TOTAL POND.</span></div>${P.map(p=>`<div class="pipeRow" onclick="openP('${p.id}')"><span><b>${esc(p.n)}</b><small>${esc(p.pipe.n)}</small></span><span>${p.totalValue?COP(p.totalValue):'POR DEFINIR'}</span><span>${pct(p.pipe.p2)}</span><span>${pipeMoney(p.pipe2)}</span><span>${pct(p.pipe.p6)}</span><span>${pipeMoney(p.pipe6)}</span><span>${pipeMoney(p.pipeT)}</span></div>`).join('')}</div>`}
const oldOpenP=openP;
openP=function(id){oldOpenP(id);const p=P.find(x=>x.id===id),box=document.querySelector('#modal .box');if(!box||!p)return;const panel=document.createElement('div');panel.className='panel pipelinePanel';panel.innerHTML=`<span>PIPELINE COMERCIAL</span><div class="pipeStats"><div><small>VALOR TOTAL</small><b>${p.totalValue?COP(p.totalValue):'POR DEFINIR'}</b></div><div><small>2 MESES · ${pct(p.pipe.p2)}</small><b>${pipeMoney(p.pipe2)}</b></div><div><small>6 MESES · ${pct(p.pipe.p6)}</small><b>${pipeMoney(p.pipe6)}</b></div><div><small>TOTAL POND. · ${pct(p.pipe.pt)}</small><b>${pipeMoney(p.pipeT)}</b></div></div><p>${esc(p.pipe.n)}</p>`;const grid=box.querySelector('.modalgrid');if(grid)grid.prepend(panel);}
const oldRender=render;
render=function(){nav();view.innerHTML=tab==='summary'?summary():tab==='projects'?projects():tab==='pipeline'?pipeline():tab==='calendar'?calendar():audit()}
